### ISSUE TITLE
early transformer uses ASM classes loaded by the system class loader, causing mod classes to not be found

### ISSUE THREAD

**Issue by UR91K** [user11681/GrossFabricHacks#11]
Client crashes immediately with only Kotlin and limitless in the mods folder. No crash report is produced, it just says Exit Code: 0 in launcher and produces 2 log files. I am using a completely clean and up to date Fabric installation and the client launches fine with either mod removed from the mods folder, it seems to be an incompatibility but it may be something else causing the crash. here are the 2 log files;
[2020-11-05-1.log](https://github.com/user11681/limitless/files/5492990/2020-11-05-1.log)
[latest.log](https://github.com/user11681/limitless/files/5492992/latest.log)

**Comment by user11681** [comment]
Thanks for the report.
